source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZZCustomAlertView_Example', :exclusive => true do
  pod "ZZCustomAlertView", :path => "../"
end

target 'ZZCustomAlertView_Tests', :exclusive => true do
  pod "ZZCustomAlertView", :path => "../"

  
end
